from typing import TypedDict

#keigo specific fields
#state or context

class KeigoState(TypedDict):
    """Keigo specific context parameters for the agent.

    Set these when creating assistants OR when invoking the graph.
    """
    raw_input: str # What the user typed
    audience: str # Extracted by Analyzer (e.g., "Client", "Boss")
    draft_keigo: str # Generated by Keigo Specialist
    feedback: str # Added by Cultural Coach if corrections are needed
    is_approved: bool # Added by Cultural Coach to determine if we stop

